"""Shared constants for the ESP32 EVSE external component."""

from esphome.const import (
    CONF_ACCURACY_DECIMALS,
    CONF_CURRENT,
    CONF_DEVICE_CLASS,
    CONF_ENERGY,
    CONF_ICON,
    CONF_STATE_CLASS,
    CONF_TEMPERATURE,
    CONF_UNIT_OF_MEASUREMENT,
    CONF_UPDATE_INTERVAL,
    CONF_VOLTAGE,
    DEVICE_CLASS_CURRENT,
    DEVICE_CLASS_ENERGY,
    DEVICE_CLASS_TEMPERATURE,
    DEVICE_CLASS_VOLTAGE,
    STATE_CLASS_MEASUREMENT,
    STATE_CLASS_TOTAL_INCREASING,
    UNIT_AMPERE,
    UNIT_CELSIUS,
    UNIT_KILOWATT_HOURS,
    UNIT_VOLT,
)

CONF_CHARGING_STATE = "charging_state"
CONF_CHARGING_SWITCH = "charging"
CONF_RESET_BUTTON = "reset"
CONF_CURRENT_LIMIT = "current_limit"

CONF_ESP32_EVSE_ID = "esp32_evse_id"

DEFAULT_UPDATE_INTERVAL = "15s"

SENSOR_DEFAULTS = {
    CONF_VOLTAGE: {
        CONF_UNIT_OF_MEASUREMENT: UNIT_VOLT,
        CONF_ACCURACY_DECIMALS: 1,
        CONF_STATE_CLASS: STATE_CLASS_MEASUREMENT,
        CONF_DEVICE_CLASS: DEVICE_CLASS_VOLTAGE,
    },
    CONF_CURRENT: {
        CONF_UNIT_OF_MEASUREMENT: UNIT_AMPERE,
        CONF_ACCURACY_DECIMALS: 2,
        CONF_STATE_CLASS: STATE_CLASS_MEASUREMENT,
        CONF_DEVICE_CLASS: DEVICE_CLASS_CURRENT,
    },
    CONF_ENERGY: {
        CONF_UNIT_OF_MEASUREMENT: UNIT_KILOWATT_HOURS,
        CONF_ACCURACY_DECIMALS: 3,
        CONF_STATE_CLASS: STATE_CLASS_TOTAL_INCREASING,
        CONF_DEVICE_CLASS: DEVICE_CLASS_ENERGY,
    },
    CONF_TEMPERATURE: {
        CONF_UNIT_OF_MEASUREMENT: UNIT_CELSIUS,
        CONF_ACCURACY_DECIMALS: 1,
        CONF_STATE_CLASS: STATE_CLASS_MEASUREMENT,
        CONF_DEVICE_CLASS: DEVICE_CLASS_TEMPERATURE,
    },
}

TEXT_SENSOR_DEFAULTS = {
    CONF_CHARGING_STATE: {
        CONF_ICON: "mdi:ev-station",
    }
}

# Mapping between configuration keys and the EVSE AT query commands.
SENSOR_QUERIES = {
    CONF_CHARGING_STATE: "AT+STATE?",
    CONF_VOLTAGE: "AT+VOLT?",
    CONF_CURRENT: "AT+CURR?",
    CONF_ENERGY: "AT+ENER?",
    CONF_TEMPERATURE: "AT+TEMP?",
}

# Mapping between configuration keys and EVSE control commands.
COMMAND_START_CHARGING = "AT+START"
COMMAND_STOP_CHARGING = "AT+STOP"
COMMAND_RESET = "AT+RESET"
COMMAND_SET_CURRENT_LIMIT = "AT+SETCUR"


