"""Constants shared across the ESP32 EVSE integration."""

from __future__ import annotations

from esphome.const import (
    CONF_CURRENT,
    CONF_ENERGY,
    CONF_ID,
    CONF_TEMPERATURE,
    CONF_UPDATE_INTERVAL,
    CONF_VOLTAGE,
)

CONF_CHARGING_STATE = "charging_state"
CONF_CHARGING_SWITCH = "charging"
CONF_RESET_BUTTON = "reset"
CONF_CURRENT_LIMIT = "current_limit"

DEFAULT_UPDATE_INTERVAL = "15s"

CONF_SENSORS = "sensors"
CONF_TEXT_SENSORS = "text_sensors"
CONF_SWITCHES = "switches"
CONF_BUTTONS = "buttons"
CONF_NUMBERS = "numbers"

# UART command strings used by the firmware.
COMMAND_PING = "AT"
COMMAND_START_CHARGING = "AT+START"
COMMAND_STOP_CHARGING = "AT+STOP"
COMMAND_RESET = "AT+RESET"
COMMAND_CURRENT_LIMIT = "AT+SETCUR"

QUERY_STATE = "AT+STATE?"
QUERY_VOLTAGE = "AT+VOLT?"
QUERY_CURRENT = "AT+CURR?"
QUERY_ENERGY = "AT+ENER?"
QUERY_TEMPERATURE = "AT+TEMP?"

RESPONSE_PREFIX_STATE = "STATE:"
RESPONSE_PREFIX_VOLTAGE = "VOLT:"
RESPONSE_PREFIX_CURRENT = "CURR:"
RESPONSE_PREFIX_ENERGY = "ENER:"
RESPONSE_PREFIX_TEMPERATURE = "TEMP:"

__all__ = [
    "CONF_BUTTONS",
    "CONF_CHARGING_STATE",
    "CONF_CHARGING_SWITCH",
    "CONF_CURRENT",
    "CONF_CURRENT_LIMIT",
    "CONF_ENERGY",
    "CONF_ID",
    "CONF_NUMBERS",
    "CONF_RESET_BUTTON",
    "CONF_SENSORS",
    "CONF_SWITCHES",
    "CONF_TEMPERATURE",
    "CONF_TEXT_SENSORS",
    "CONF_UPDATE_INTERVAL",
    "CONF_VOLTAGE",
    "COMMAND_CURRENT_LIMIT",
    "COMMAND_PING",
    "COMMAND_RESET",
    "COMMAND_START_CHARGING",
    "COMMAND_STOP_CHARGING",
    "DEFAULT_UPDATE_INTERVAL",
    "QUERY_CURRENT",
    "QUERY_ENERGY",
    "QUERY_STATE",
    "QUERY_TEMPERATURE",
    "QUERY_VOLTAGE",
    "RESPONSE_PREFIX_CURRENT",
    "RESPONSE_PREFIX_ENERGY",
    "RESPONSE_PREFIX_STATE",
    "RESPONSE_PREFIX_TEMPERATURE",
    "RESPONSE_PREFIX_VOLTAGE",
]
